Refactor speed.js
Signature-Sound-Vienna/mei-friend-online pull request #8
Opened 2022-11-05 08:07 UTC by th-we

This mainly adds TypeScript support by means of JSDoc comments. The original motivation to work with the code was to make speed.js usable in a node.js context.  This would not only allow re-use by third party but would also simplify writing tests. That's why I made everything work without the global `window.document` object in a77fd168343b9e19cbb90fbee5fb58bfcffd00a4.

2022-11-09 09:57 UTC, wergo commented on app/static/lib/speed.js
> +          let staffDef = spdScore.querySelector(`staffDef[n=${staffNo}]`);
Here it crashes, double quotes missing for `@n`: should be ``spdScore.querySelector(`staffDef[n="${staffNo}"]`);``

2022-11-09 11:14 UTC, wergo commented on app/static/lib/speed.js
> +    const m = /** @type {Element} */ (spdScore.querySelector('[*|id="endingMeasure"]'));
`m` should be the `startingMeasure` (not `endingMeasure`)

2022-11-09 15:15 UTC, wergo requested changes
There are four little things to change. Please see comments...

2022-11-09 21:57 UTC, th-we commented on app/static/lib/speed.js
> -  let breaksOption = document.getElementById('breaks-select').value;
Oh yes, I only changed it in [one place](https://github.com/notengrafik/mei-friend-online/blob/089adfda789e0975430af2c7127ba87a9f97b758/app/static/lib/viewer.js#L89), but not the others.  Pushed a nother commit to the pull request.

2022-11-09 22:07 UTC, th-we commented on app/static/lib/speed.js
> -  let breaksOption = document.getElementById('breaks-select').value;
Oh yes, I only changed it in [one place](https://github.com/notengrafik/mei-friend-online/blob/089adfda789e0975430af2c7127ba87a9f97b758/app/static/lib/viewer.js#L89), but not the others.  Pushed a nother commit to the pull request.

2022-11-09 22:08 UTC, th-we commented on app/static/lib/speed.js
> +  if (Object.keys(pageSpanners.start).length > 0)
I'd rather change [the code in `resizer.js` line](https://github.com/Signature-Sound-Vienna/mei-friend-online/blob/3d55b819e95b4dc2cbc4349c8a9efeca814ab5ad/app/static/lib/resizer.js#L137) to `v.pageSpanners = {start: {}, end: {}}`. If we don't, we have to change [the type](https://github.com/notengrafik/mei-friend-online/blob/089adfda789e0975430af2c7127ba87a9f97b758/app/static/lib/speed.js#L16): to this:

```
@typedef {{
  start?: {[pageNum: string]: string[]},
  end?: {[pageNum: string]: string[]}
}} PageSpanners;
```

With that change, I get more errors [here](https://github.com/notengrafik/mei-friend-online/blob/089adfda789e0975430af2c7127ba87a9f97b758/app/static/lib/speed.js#L609) and [here](https://github.com/notengrafik/mei-friend-online/blob/089adfda789e0975430af2c7127ba87a9f97b758/app/static/lib/speed.js#L629).

So I added the change in resize.js to the pull request.

2022-11-13 10:35 UTC, merged

2022-11-13 10:36 UTC, wergo commented
Thanks a lot for the changes!